name: Build with Tests

on: 
    pull_request:
        branches: 
            - main
            - development

env:
    DOTNET_VERSION: 4.8

jobs: 
    test:
        name: Build and Test
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - uses: microsoft/setup-msbuild@v1
            - uses: NuGet/setup-nuget@v1.1.1
            - uses: darenm/Setup-VSTest@v1.2

            - name: Restore Nuget Packages
              id: restore
              run: |
                nuget restore SudokuSolve.sln

            - name: Build Solution
              id: buildsolution
              run: |
                msbuild.exe SudokuSolve.sln -t:BuildPayEngine -property:Configuration=Release
              shell: cmd

            - name: Run Architectural Tests - Persona Clock Unit
              id: architecturaltestspersonaclock
              run: |
                vstest.console.exe **\bin\$(Configuration)\**\Sudoku.GameBoard.Tests.dll /logger:trx
              shell: cmd

